version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bank-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BankDevsu123
    ports:
      - "1433:1433"
    networks:
      - bank-network
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]

  bankapi:
    build:
      context: .
      dockerfile: BankDevsu.Api/Dockerfile
    container_name: bankdevsuapi
    environment:
      - DB_CONN=Server=sqlserver,1433;Database=BankingDb;User Id=sa;Password=BankDevsu123;TrustServerCertificate=True;
    ports:
      - "32768:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - bank-network

networks:
  bank-network:

volumes:
  sqlserver-data:
